insert into payments (order_id, payment_method, refund) values (1, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (2, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (3, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (4, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (5, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (6, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (7, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (8, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (9, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (10, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (11, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (12, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (13, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (14, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (15, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (16, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (17, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (18, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (19, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (20, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (21, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (22, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (23, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (24, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (25, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (26, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (27, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (28, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (29, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (30, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (31, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (32, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (33, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (34, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (35, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (36, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (37, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (38, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (39, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (40, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (41, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (42, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (43, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (44, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (45, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (46, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (47, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (48, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (49, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (50, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (51, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (52, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (53, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (54, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (55, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (56, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (57, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (58, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (59, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (60, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (61, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (62, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (63, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (64, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (65, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (66, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (67, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (68, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (69, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (70, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (71, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (72, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (73, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (74, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (75, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (76, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (77, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (78, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (79, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (80, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (81, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (82, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (83, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (84, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (85, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (86, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (87, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (88, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (89, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (90, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (91, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (92, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (93, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (94, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (95, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (96, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (97, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (98, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (99, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (100, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (101, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (102, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (103, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (104, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (105, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (106, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (107, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (108, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (109, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (110, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (111, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (112, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (113, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (114, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (115, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (116, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (117, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (118, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (119, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (120, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (121, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (122, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (123, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (124, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (125, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (126, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (127, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (128, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (129, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (130, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (131, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (132, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (133, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (134, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (135, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (136, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (137, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (138, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (139, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (140, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (141, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (142, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (143, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (144, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (145, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (146, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (147, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (148, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (149, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (150, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (151, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (152, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (153, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (154, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (155, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (156, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (157, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (158, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (159, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (160, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (161, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (162, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (163, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (164, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (165, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (166, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (167, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (168, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (169, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (170, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (171, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (172, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (173, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (174, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (175, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (176, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (177, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (178, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (179, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (180, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (181, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (182, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (183, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (184, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (185, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (186, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (187, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (188, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (189, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (190, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (191, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (192, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (193, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (194, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (195, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (196, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (197, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (198, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (199, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (200, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (201, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (202, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (203, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (204, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (205, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (206, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (207, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (208, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (209, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (210, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (211, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (212, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (213, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (214, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (215, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (216, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (217, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (218, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (219, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (220, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (221, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (222, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (223, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (224, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (225, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (226, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (227, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (228, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (229, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (230, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (231, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (232, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (233, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (234, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (235, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (236, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (237, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (238, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (239, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (240, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (241, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (242, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (243, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (244, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (245, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (246, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (247, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (248, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (249, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (250, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (251, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (252, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (253, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (254, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (255, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (256, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (257, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (258, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (259, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (260, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (261, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (262, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (263, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (264, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (265, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (266, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (267, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (268, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (269, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (270, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (271, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (272, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (273, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (274, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (275, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (276, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (277, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (278, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (279, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (280, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (281, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (282, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (283, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (284, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (285, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (286, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (287, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (288, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (289, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (290, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (291, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (292, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (293, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (294, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (295, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (296, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (297, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (298, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (299, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (300, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (301, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (302, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (303, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (304, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (305, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (306, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (307, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (308, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (309, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (310, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (311, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (312, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (313, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (314, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (315, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (316, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (317, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (318, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (319, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (320, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (321, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (322, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (323, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (324, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (325, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (326, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (327, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (328, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (329, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (330, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (331, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (332, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (333, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (334, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (335, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (336, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (337, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (338, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (339, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (340, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (341, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (342, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (343, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (344, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (345, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (346, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (347, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (348, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (349, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (350, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (351, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (352, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (353, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (354, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (355, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (356, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (357, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (358, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (359, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (360, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (361, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (362, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (363, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (364, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (365, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (366, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (367, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (368, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (369, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (370, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (371, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (372, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (373, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (374, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (375, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (376, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (377, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (378, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (379, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (380, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (381, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (382, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (383, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (384, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (385, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (386, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (387, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (388, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (389, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (390, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (391, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (392, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (393, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (394, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (395, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (396, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (397, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (398, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (399, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (400, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (401, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (402, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (403, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (404, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (405, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (406, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (407, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (408, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (409, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (410, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (411, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (412, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (413, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (414, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (415, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (416, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (417, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (418, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (419, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (420, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (421, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (422, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (423, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (424, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (425, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (426, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (427, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (428, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (429, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (430, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (431, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (432, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (433, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (434, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (435, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (436, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (437, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (438, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (439, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (440, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (441, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (442, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (443, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (444, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (445, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (446, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (447, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (448, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (449, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (450, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (451, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (452, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (453, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (454, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (455, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (456, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (457, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (458, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (459, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (460, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (461, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (462, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (463, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (464, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (465, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (466, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (467, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (468, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (469, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (470, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (471, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (472, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (473, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (474, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (475, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (476, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (477, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (478, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (479, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (480, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (481, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (482, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (483, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (484, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (485, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (486, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (487, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (488, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (489, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (490, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (491, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (492, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (493, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (494, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (495, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (496, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (497, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (498, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (499, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (500, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (501, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (502, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (503, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (504, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (505, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (506, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (507, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (508, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (509, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (510, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (511, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (512, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (513, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (514, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (515, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (516, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (517, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (518, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (519, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (520, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (521, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (522, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (523, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (524, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (525, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (526, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (527, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (528, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (529, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (530, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (531, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (532, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (533, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (534, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (535, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (536, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (537, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (538, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (539, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (540, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (541, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (542, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (543, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (544, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (545, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (546, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (547, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (548, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (549, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (550, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (551, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (552, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (553, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (554, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (555, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (556, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (557, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (558, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (559, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (560, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (561, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (562, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (563, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (564, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (565, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (566, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (567, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (568, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (569, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (570, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (571, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (572, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (573, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (574, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (575, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (576, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (577, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (578, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (579, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (580, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (581, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (582, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (583, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (584, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (585, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (586, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (587, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (588, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (589, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (590, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (591, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (592, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (593, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (594, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (595, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (596, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (597, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (598, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (599, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (600, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (601, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (602, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (603, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (604, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (605, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (606, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (607, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (608, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (609, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (610, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (611, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (612, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (613, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (614, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (615, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (616, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (617, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (618, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (619, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (620, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (621, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (622, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (623, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (624, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (625, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (626, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (627, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (628, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (629, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (630, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (631, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (632, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (633, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (634, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (635, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (636, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (637, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (638, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (639, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (640, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (641, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (642, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (643, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (644, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (645, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (646, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (647, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (648, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (649, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (650, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (651, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (652, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (653, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (654, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (655, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (656, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (657, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (658, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (659, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (660, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (661, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (662, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (663, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (664, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (665, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (666, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (667, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (668, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (669, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (670, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (671, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (672, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (673, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (674, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (675, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (676, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (677, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (678, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (679, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (680, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (681, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (682, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (683, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (684, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (685, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (686, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (687, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (688, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (689, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (690, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (691, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (692, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (693, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (694, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (695, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (696, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (697, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (698, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (699, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (700, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (701, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (702, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (703, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (704, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (705, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (706, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (707, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (708, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (709, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (710, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (711, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (712, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (713, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (714, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (715, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (716, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (717, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (718, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (719, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (720, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (721, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (722, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (723, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (724, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (725, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (726, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (727, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (728, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (729, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (730, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (731, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (732, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (733, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (734, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (735, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (736, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (737, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (738, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (739, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (740, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (741, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (742, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (743, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (744, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (745, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (746, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (747, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (748, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (749, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (750, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (751, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (752, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (753, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (754, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (755, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (756, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (757, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (758, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (759, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (760, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (761, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (762, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (763, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (764, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (765, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (766, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (767, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (768, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (769, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (770, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (771, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (772, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (773, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (774, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (775, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (776, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (777, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (778, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (779, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (780, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (781, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (782, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (783, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (784, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (785, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (786, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (787, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (788, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (789, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (790, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (791, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (792, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (793, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (794, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (795, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (796, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (797, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (798, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (799, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (800, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (801, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (802, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (803, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (804, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (805, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (806, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (807, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (808, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (809, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (810, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (811, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (812, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (813, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (814, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (815, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (816, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (817, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (818, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (819, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (820, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (821, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (822, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (823, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (824, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (825, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (826, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (827, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (828, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (829, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (830, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (831, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (832, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (833, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (834, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (835, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (836, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (837, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (838, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (839, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (840, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (841, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (842, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (843, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (844, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (845, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (846, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (847, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (848, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (849, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (850, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (851, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (852, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (853, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (854, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (855, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (856, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (857, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (858, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (859, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (860, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (861, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (862, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (863, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (864, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (865, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (866, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (867, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (868, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (869, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (870, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (871, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (872, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (873, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (874, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (875, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (876, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (877, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (878, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (879, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (880, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (881, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (882, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (883, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (884, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (885, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (886, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (887, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (888, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (889, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (890, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (891, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (892, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (893, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (894, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (895, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (896, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (897, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (898, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (899, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (900, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (901, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (902, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (903, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (904, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (905, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (906, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (907, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (908, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (909, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (910, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (911, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (912, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (913, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (914, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (915, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (916, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (917, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (918, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (919, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (920, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (921, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (922, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (923, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (924, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (925, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (926, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (927, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (928, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (929, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (930, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (931, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (932, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (933, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (934, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (935, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (936, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (937, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (938, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (939, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (940, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (941, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (942, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (943, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (944, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (945, 'Netbanking', 'NA');
insert into payments (order_id, payment_method, refund) values (946, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (947, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (948, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (949, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (950, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (951, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (952, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (953, 'UPI', 'NA');
insert into payments (order_id, payment_method, refund) values (954, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (955, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (956, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (957, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (958, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (959, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (960, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (961, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (962, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (963, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (964, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (965, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (966, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (967, 'UPI', 'done');
insert into payments (order_id, payment_method, refund) values (968, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (969, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (970, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (971, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (972, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (973, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (974, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (975, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (976, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (977, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (978, 'COD', 'NA');
insert into payments (order_id, payment_method, refund) values (979, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (980, 'Bank Transfer', 'done');
insert into payments (order_id, payment_method, refund) values (981, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (982, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (983, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (984, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (985, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (986, 'UPI', 'rejected');
insert into payments (order_id, payment_method, refund) values (987, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (988, 'COD', 'done');
insert into payments (order_id, payment_method, refund) values (989, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (990, 'Bank Transfer', 'rejected');
insert into payments (order_id, payment_method, refund) values (991, 'Bank Transfer', 'initiated');
insert into payments (order_id, payment_method, refund) values (992, 'UPI', 'initiated');
insert into payments (order_id, payment_method, refund) values (993, 'Netbanking', 'rejected');
insert into payments (order_id, payment_method, refund) values (994, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (995, 'Bank Transfer', 'NA');
insert into payments (order_id, payment_method, refund) values (996, 'COD', 'rejected');
insert into payments (order_id, payment_method, refund) values (997, 'Netbanking', 'done');
insert into payments (order_id, payment_method, refund) values (998, 'Netbanking', 'initiated');
insert into payments (order_id, payment_method, refund) values (999, 'COD', 'initiated');
insert into payments (order_id, payment_method, refund) values (1000, 'Bank Transfer', 'done');
